spring:
  security:
    whitelist:
      - /webjars/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /doc.html**
    staticlist:
      - /**/*.js
      - /**/*.css
      - /**/*.ico
      - /assets/**
      - /css/**
      - /images/**