spring:
  security:
    connect_check_token_url:
      - http://localhost:8080/oauth2/v1/check_token
    whitelist:
      - /*/wagger-ui.html**
      - /*/doc.html**
    staticlist:
      - /assets/**
      - /css/**
      - /images/**
      - /js/**
      - /img/**
      #以下是透出swagger，即doc.html
      - /*/webjars/**
      - /*/swagger-resources**
      - /*/*/api-docs**
      - /*/*.css
      - /*/*.json
      - /*/*.js
      - /*/*.ico
      - /*/*.jpg
      - /*/*.png
