spring:
  security:
    connect_check_token_url:
      - ${cj.geochat.connect_check_token_url:http://localhost:9000/oauth2/v1/check_token}
    whitelist:
      - /*/public/v**
      - /*/swagger-ui.html**
      - /*/doc.html**
      - /*/v3/api-docs/**
    staticlist:
      - /assets/**
      - /css/**
      - /images/**
      - /js/**
      - /img/**
      #以下是透出swagger，即doc.html
      - /*/webjars/**
      - /*/swagger-resources**
      - /*/*/api-docs**
      - /*/*.css
      - /*/*.json
      - /*/*.js
      - /*/*.ico
      - /*/*.jpg
      - /*/*.png